# Change baseurl before deploy
baseurl = "https://goisra.github.io/WHEX"
languageCode = "en-us"
paginate = 5
title = "Israel Jesús"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

<div>
<a href="https://n9.cl/p40yg" target="_blank"><img src="https://dgsamper.github.io/chatbot-icon/" title="Chatbot" alt="Chatbot" width="40" height="40"/></a>
</div>


